$schema: 'https://schema.getpostman.com/json/collection/v2.1.0/environment.json'
$kind: environment
name: CNC Store - Development
values:
  - key: baseUrl
    value: 'http://localhost:4000'
    enabled: true
    secret: false
  - key: authToken
    value: ''
    enabled: true
    secret: true
  - key: adminToken
    value: ''
    enabled: true
    secret: true
  - key: productId
    value: ''
    enabled: true
    secret: false
  - key: productSlug
    value: ''
    enabled: true
    secret: false
  - key: orderId
    value: ''
    enabled: true
    secret: false
  - key: customOrderId
    value: ''
    enabled: true
    secret: false
